---
  - hosts: webserver
    become: T
    tasks:
      - name: To Install All Other Stuffs
        apt: >
            name={{item}}
            state=present
            update_cache=yes
        with_items:
          - apache2
          - libapache2-mod-wsgi
          - python-pip
          - python-virtualenv

      - name: ensure apache2 is running
        service: name=apache2 state=started enabled=yes
