---
  - hosts: webserver
    become: T
    tasks:
      - name: To Install All Other Stuffs
        apt: >
            name={{item}}
            state=present
            update_cache=yes
        with_items:
          - apache2
          - libapache2-mod-wsgi
          - python-pip
          - python-virtualenv

      - name: ensure apache2 is running
        service: name=apache2 state=started enabled=yes

      - name: ensure mod_wsgi enabled
        apache2_module: state=present name=wsgi
        notify: restart apache2

      - name: copy demo app source
        copy: src=/home/ansible/work/ansible/demo/app/ dest=/var/www/demo mode=0755
        notify: restart apache2

      - name: copy apache related file
        copy: src=/home/ansible/work/ansible/demo/demo.conf dest=/etc/apache2/sites-available mode=0755
        notify: restart apache handler

    handlers:
      - name: restart apache2
        service: name=apache2 state=restarted
